<?php

namespace App\DataFixtures;

use App\Entity\Articles;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Faker\Factory;

// @codingStandardsIgnoreStart

class ArticlesFixtures extends Fixture
{
    const ARTICLES = [
        [
            "title" => "Au Japon, vous pouvez désormais être condamné",
            "image" => "https://www.01net.com/app/uploads/2022/07/koukichi-takahashi-fZdX9BW8WDs-unsplash.jpg",
            "articleContent" => '<div class="post-excerpt">
            <p><strong><span style="font-size: 18pt;">Le Japon durcit la loi contre les insultes publi&eacute;es sur les r&eacute;seaux sociaux avec une hausse cons&eacute;quence sur les amendes et les peines de prison. Mais cela pourrait constituer une entrave &agrave; la libert&eacute; d&rsquo;expression.</span></strong></p>
            </div>
            <div class="od-wrapper od-background">&nbsp;</div>
            <div class="entry-content prose dark:prose-invert lg:prose-lg max-w-none mt-5">
            <p>Les utilisateurs de r&eacute;seaux sociaux au Japon vont devoir faire tr&egrave;s attention &agrave; ce qu&rsquo;ils publient. Une nouvelle loi vient d&rsquo;entrer en vigueur qui r&eacute;vise le code p&eacute;nal et durcit les sanctions pour les auteurs d&rsquo;insultes en ligne. L&rsquo;amende maximale passe de 10 000 yens (environ 70 euros) &agrave; 300 000 yens (environ 2160 euros). Mais ce sont surtout les peines de prison qui deviennent dissuasives&nbsp;:&nbsp; jusqu&rsquo;&agrave; un an contre moins de 30 jours pr&eacute;c&eacute;demment.</p>
            <p>Ce changement est intervenu en r&eacute;action au suicide en 2020 d&rsquo;Hana Kimura, une catcheuse et actrice de 22 ans. Elle avait particip&eacute; &agrave; l&rsquo;&eacute;mission de t&eacute;l&eacute;r&eacute;alit&eacute;&nbsp;<em>Terrace House</em>&nbsp;de Netflix. Son suicide &eacute;tait survenu apr&egrave;s avoir re&ccedil;u un flot de messages haineux sur les r&eacute;seaux sociaux. Deux hommes ont &eacute;t&eacute; condamn&eacute;s &agrave; des amendes de 9000 yens chacun, mais des voix se sont &eacute;lev&eacute;es pour critiquer les peines, jug&eacute;es trop l&eacute;g&egrave;res.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>Notons que des partis d&rsquo;opposition se sont oppos&eacute;s &agrave; ce changement de la loi, arguant qu&rsquo;elle pourrait emp&ecirc;cher les critiques l&eacute;gitimes des politiciens et des fonctionnaires sur les r&eacute;seaux sociaux.</p>
            <h2>Trois ans pour voir si la loi ne pose pas de probl&egrave;me de libert&eacute; d&rsquo;expression</h2>
            <p>C&rsquo;est pour cela que cette nouvelle mesure sera r&eacute;&eacute;valu&eacute;e au bout de trois ans, histoire de v&eacute;rifier qu&rsquo;elle ne porte pas atteinte &agrave; la libert&eacute; d&rsquo;expression. Le ministre japonais de la Justice, Yoshihisa Furukawa, a d&eacute;clar&eacute; que ce durcissement des sanctions agit comme un moyen de dissuasion et montre que le cyberharc&egrave;lement est un crime qui doit &ecirc;tre s&eacute;v&egrave;rement r&eacute;prim&eacute;.</p>
            <p>Mais cette loi pose le probl&egrave;me de la d&eacute;finition d&rsquo;une insulte, qui peut &ecirc;tre diff&eacute;rente d&rsquo;un pays &agrave; l&rsquo;autre. Interrog&eacute; par nos confr&egrave;res de&nbsp;<a href="https://www.cnn.com/2022/06/14/asia/japan-cyberbullying-law-intl-hnk-scli/index.html">CNN</a>, Seiho Cho, un avocat p&eacute;naliste au Japon, explique qu&rsquo;il n&rsquo;y a pas de d&eacute;finition claire. La loi dit juste&nbsp;qu&rsquo;insulter&nbsp;quelqu&rsquo;un consiste &agrave; le d&eacute;grader sans un fait sp&eacute;cifique &agrave; son sujet, par opposition &agrave; la diffamation. Selon Seiho Cho, si quelqu&rsquo;un traite le dirigeant du Japon d&rsquo;idiot, alors peut-&ecirc;tre que cela pourrait &ecirc;tre consid&eacute;r&eacute; comme une insulte en vertu de la nouvelle loi.</p>
            </div>',
            "articleSumary" => "Au Japon, vous pouvez désormais être condamné jusqu’à un an de prison si vous insultez quelqu’un en ligne",
            "date" => ""
        ],
        [
            "title" => "Conduite autonome",
            "image" => "https://www.01net.com/app/uploads/2022/07/vehicule-autonome.jpg",
            "articleContent" => '<div class="post-excerpt">
            <p><strong><span style="font-size: 18pt;">D&rsquo;ici &agrave; quelques semaines, il sera l&eacute;gal de conduire en levant les mains du volant en France. Un d&eacute;cret qui concerne uniquement les v&eacute;hicules &eacute;quip&eacute;s d&rsquo;un syst&egrave;me de pilotage automatique de niveau 3.</span></strong></p>
            <p>Conduire sans les mains sur le volant sera autoris&eacute; &agrave; partir du 1er septembre 2022 en France pour les v&eacute;hicules proposant un syst&egrave;me de pilotage dit &laquo; automatique &raquo; de niveau 3. Les voitures &eacute;quip&eacute;es d&rsquo;un tel syst&egrave;me pourront uniquement rouler dans certaines zones autoris&eacute;es.</p>
            </div>
            <div class="entry-content prose dark:prose-invert lg:prose-lg max-w-none mt-5">
            <h2>Conduire sans poser les mains sur le volant devient une r&eacute;alit&eacute; en France</h2>
            <p><a href="https://www.01net.com/actualites/conduite-autonome-de-niveau-3-en-juillet-vous-n-aurez-plus-besoin-de-poser-les-mains-sur-le-volant-2055012.html">Nous vous en parlions en f&eacute;vrier dernier</a>, cette autorisation entre en vigueur au niveau europ&eacute;en &agrave; partir du 14 juillet. Mais il faudra attendre le mois de septembre 2022 pour pouvoir r&eacute;ellement conduire sans les mains dans l&rsquo;Hexagone. Le code de la route et des transports s&rsquo;adapte &agrave; l&rsquo;arriv&eacute;e des v&eacute;hicules autonomes sur les routes fran&ccedil;aises, apr&egrave;s un d&eacute;cret le 1er juillet 2021 qui prendra effet le 1er septembre de cette ann&eacute;e.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>Jusqu&rsquo;&agrave; pr&eacute;sent, l&rsquo;autonomie de niveau 2 (sur cinq) utilise deux technologies&nbsp;: celle de l&rsquo;aide au maintien sur la voie et le r&eacute;gulateur adaptatif de vitesse. Pratiques, elles n&eacute;cessitent cependant que le conducteur garde les mains sur le volant. Une &laquo;&nbsp;contrainte&nbsp;&raquo; qui sera lev&eacute;e en passant au niveau 3. N&eacute;anmoins, la personne au volant doit &ecirc;tre en mesure de reprendre la main sur la conduite si n&eacute;cessaire.</p>
            <p>Vous vous en doutez, toutes les routes n&rsquo;autorisent pas la conduite autonome de niveau 3. Seules certaines zones sont concern&eacute;es. Elles doivent r&eacute;pondre &agrave; trois conditions&nbsp;: la vitesse maximale autoris&eacute;e ne doit pas d&eacute;passer 60 km/h, la voie de circulation doit &ecirc;tre sans cyclistes ni pi&eacute;tons et une s&eacute;paration physique doit exister entre les deux sens de circulation (barri&egrave;re ou terre-plein par exemple).</p>
            <h2>Non, vous ne pourrez toujours pas faire la sieste au volant</h2>
            <p>Nous sommes encore assez loin du niveau 4 o&ugrave; la pr&eacute;sence du conducteur n&rsquo;est requise que sur certaines routes, ou du niveau 5 o&ugrave; le v&eacute;hicule peut se passer de chauffeur. Le niveau 3 demande &agrave; la personne au volant de pouvoir reprendre le contr&ocirc;le de la voiture en cas de probl&egrave;me. Dans les zones autoris&eacute;es uniquement, le v&eacute;hicule se chargera de l&rsquo;acc&eacute;l&eacute;ration, du freinage, de la direction et de la surveillance de la route.</p>
            <p>L&rsquo;autorisation du niveau 3 de conduite autonome apporte &eacute;galement des changements importants au niveau de la l&eacute;gislation. En effet, si le v&eacute;hicule se trouve impliqu&eacute; dans un accident d&ucirc; &agrave; un d&eacute;faut du pilotage automatique, c&rsquo;est le constructeur du v&eacute;hicule et non le conducteur qui serait tenu pour responsable.</p>
            <p>Une responsabilit&eacute; importante p&egrave;se donc sur les marques de v&eacute;hicules proposant cette fonctionnalit&eacute;. En France, c&rsquo;est&nbsp;<a href="https://www.01net.com/actualites/mercedes-grille-la-politesse-a-tesla-pour-la-conduite-autonome-de-niveau-3-en-france-2052560.html">Mercedes qui a pris de l&rsquo;avance sur Tesla dans ce domaine</a>. En effet, le EQS 100&nbsp;% &eacute;lectrique du fabricant allemand sera le premier v&eacute;hicule de niveau 3 autoris&eacute; &agrave; rouler dans l&rsquo;hexagone d&egrave;s septembre 2022.</p>
            <p>Il faudra atteindre encore quelques ann&eacute;es pour passer au niveau 4 dans nos contr&eacute;es. Les entreprises sp&eacute;cialis&eacute;es dans les syst&egrave;mes anti-collisions et d&rsquo;assistance &agrave; la conduite de v&eacute;hicules travaillent d&eacute;j&agrave; sur&nbsp;<a href="https://www.01net.com/actualites/mobileye-presente-eyeq-ultra-la-puce-qui-promet-la-vraie-conduite-autonome-de-niveau-4-en-2025-2053334.html">des puces qui promettent une &laquo;&nbsp;vraie&nbsp;&raquo; conduite autonome</a>.</p>
            </div>',
            "articleSumary" => "Conduite autonome : on pourra très bientôt lâcher le volant en France",
            "date" => ""
        ],
        [
            "title" => "Coupe du monde de foot 2022",
            "image" => "https://www.01net.com/app/uploads/2022/07/technologie-semi-automatique-hors-jeu.jpg",
            "articleContent" => '<div class="post-excerpt">
            <p>Pour la prochaine coupe du monde de football qui aura lieu cette ann&eacute;e au Qatar, la FIFA annonce qu&rsquo;elle utilisera la technologie semi-automatis&eacute;e pour d&eacute;tecter le hors-jeu avec une pr&eacute;cision diabolique.</p>
            </div>
            <div class="od-wrapper od-background">&nbsp;</div>
            <div class="entry-content prose dark:prose-invert lg:prose-lg max-w-none mt-5">
            <p>Pour &eacute;viter au maximum les erreurs d&rsquo;arbitrage pendant la prochaine coupe du monde de football, la F&eacute;d&eacute;ration internationale de football association (FIFA) utilisera une technologie &eacute;prouv&eacute;e qui analyse les moindres mouvements des joueurs et du ballon afin de d&eacute;tecter une position de hors-jeu avant de la transmettre aux arbitres vid&eacute;o.</p>
            <h2>La fin des pol&eacute;miques sur le hors-jeu durant les matchs de foot</h2>
            <p>Les passionn&eacute;s de football le savent, un bon ou un mauvais arbitrage peut compl&egrave;tement changer l&rsquo;issue d&rsquo;un match. Pour &eacute;viter les erreurs, la technologie vient assister les arbitres qui pourront ainsi prendre les d&eacute;cisions les plus &eacute;clair&eacute;es possible. Apr&egrave;s avoir test&eacute; l&rsquo;arbitrage vid&eacute;o pendant&nbsp;<a href="https://www.01net.com/actualites/en-mai-fifa-18-annoncait-une-victoire-de-la-france-a-la-coupe-du-monde-de-football-1490791.html">la coupe du monde 2018</a>, la FIFA va l&rsquo;am&eacute;liorer cette ann&eacute;e gr&acirc;ce &agrave; cette nouvelle technologie qui utilise l&rsquo;intelligence artificielle.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>Ce sont pas moins de 12 cam&eacute;ras qui seront positionn&eacute;es sous le toit du stade pour ne rien rater du d&eacute;placement des joueurs et du ballon. Elles permettront de contr&ocirc;ler 50 fois par seconde jusqu&rsquo;&agrave; 29 points de donn&eacute;es sur les joueurs. L&rsquo;objectif est de voir pr&eacute;cis&eacute;ment si une partie du corps (t&ecirc;te, tronc ou jambes) est en position de hors-jeu.</p>
            <figure id="attachment_1093364" class="wp-caption aligncenter" style="text-align: center;" aria-describedby="caption-attachment-1093364"><img class="wp-image-1093364 size-large cursor-pointer" style="display: block; margin-left: auto; margin-right: auto;" src="https://www.01net.com/app/uploads/2022/07/ballon-coupe-du-monde-fifa-2022-1024x658.jpg" sizes="(max-width: 1024px) 100vw, 1024px" srcset="https://www.01net.com/app/uploads/2022/07/ballon-coupe-du-monde-fifa-2022-1024x658.jpg 1024w, https://www.01net.com/app/uploads/2022/07/ballon-coupe-du-monde-fifa-2022-300x193.jpg 300w, https://www.01net.com/app/uploads/2022/07/ballon-coupe-du-monde-fifa-2022-768x493.jpg 768w, https://www.01net.com/app/uploads/2022/07/ballon-coupe-du-monde-fifa-2022-50x32.jpg 50w, https://www.01net.com/app/uploads/2022/07/ballon-coupe-du-monde-fifa-2022.jpg 1200w" alt="ballon coupe du monde fifa 2022" width="1000" height="643" loading="lazy" data-index="0">
            <figcaption id="caption-attachment-1093364" class="wp-caption-text">Ballon officiel de la coupe du monde 2022 &ndash; &copy; FIFA</figcaption>
            </figure>
            <p>Mais ces donn&eacute;es ne serviraient &agrave; rien si on ne pouvait pas d&eacute;terminer le moment pr&eacute;cis auquel un joueur fait la passe &agrave; son co&eacute;quipier. C&rsquo;est l&agrave; qu&rsquo;intervient&nbsp;<em>&laquo;&nbsp;Al Rihla&nbsp;&raquo;</em>, le ballon officiel de la coupe du monde 2022 au Qatar. Au c&oelig;ur de ce ballon se trouve un capteur d&rsquo;unit&eacute; de mesure inertielle qui envoie 500 fois par seconde des donn&eacute;es &agrave; la salle de visionnage pour d&eacute;tecter le plus exactement possible le moment o&ugrave; le joueur touche le ballon pour faire sa passe.</p>
            <h2>Une aide pr&eacute;cieuse pour les arbitres vid&eacute;o</h2>
            <p>Les donn&eacute;es transmises par le ballon et celles obtenues par les joueurs gr&acirc;ce aux cam&eacute;ras combin&eacute;es &agrave; l&rsquo;intelligence artificielle permettent aux arbitres vid&eacute;o de&nbsp;<a href="https://www.01net.com/actualites/coupe-du-monde-2022-les-hors-jeu-pourraient-etre-detectes-automatiquement-par-une-ia-2051770.html">recevoir une alerte automatiquement en cas de hors-jeu</a>. Ces derniers devront ensuite valider la d&eacute;cision avant de la transmettre &agrave; l&rsquo;arbitre sur le terrain. On parle ici d&rsquo;un processus qui ne prend que quelques secondes, ce qui permet de prendre des d&eacute;cisions tr&egrave;s rapidement.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>Le l&eacute;gendaire arbitre Pierluigi Collina, aujourd&rsquo;hui pr&eacute;sident de la commission des arbitres de la FIFA, salue &eacute;galement cette avanc&eacute;e technologique&nbsp;:</p>
            <blockquote>
            <p>&laquo;&nbsp;<em>Nous savons que, parfois, le processus de v&eacute;rification d&rsquo;un &eacute;ventuel hors-jeu prend trop de temps, surtout lorsque cela se joue &agrave; quelques centim&egrave;tres. C&rsquo;est l&agrave; que la technologie semi-automatis&eacute;e de d&eacute;tection du hors-jeu s&rsquo;av&egrave;re cruciale&nbsp;: pour permettre des d&eacute;cisions plus rapides et plus pr&eacute;cises</em>.&nbsp;&raquo;</p>
            </blockquote>
            <p>Les spectateurs pourront &eacute;galement profiter de cette technologie. Une fois la d&eacute;cision valid&eacute;e par les arbitres, les donn&eacute;es seront transpos&eacute;es en animation 3D qui montrera sous le meilleur angle possible le positionnement des joueurs et du ballon au moment o&ugrave; il a &eacute;t&eacute; touch&eacute;. Cette animation sera diffus&eacute;e sur les &eacute;crans g&eacute;ants du stade et mise &agrave; disposition des chaines de t&eacute;l&eacute;vision diffusant le match.</p>
            </div>',
            "articleSumary" => "Coupe du monde de foot 2022 : la FIFA utilisera un ballon connecté pour détecter un hors-jeu",
            "date" => ""
        ],
        [
            "title" => "Facebook a eu accès à vos données supprimées, selon cet ancien employé",
            "image" => "https://www.01net.com/app/uploads/2022/07/facebook.jpg",
            "articleContent" => '<div class="post-excerpt">
            <p><strong><span style="font-size: 18pt;">Facebook est de nouveau sous le feu des projecteurs apr&egrave;s une plainte d&eacute;pos&eacute;e par un ancien employ&eacute;. Ce dernier affirme que l&rsquo;entreprise avait acc&egrave;s aux donn&eacute;es supprim&eacute;es des utilisateurs de Facebook et qu&rsquo;il a &eacute;t&eacute; licenci&eacute; pour avoir remis en cause cette pratique.</span></strong></p>
            </div>
            <div class="od-wrapper od-background">&nbsp;</div>
            <div class="entry-content prose dark:prose-invert lg:prose-lg max-w-none mt-5">
            <p>Facebook aurait eu acc&egrave;s &agrave; des donn&eacute;es utilisateurs supprim&eacute;es. C&rsquo;est ce qu&rsquo;affirme Brennan Lawson, qui poursuit en justice le groupe Meta et demande 3 millions de dollars de dommages et int&eacute;r&ecirc;ts pour avoir &eacute;t&eacute; licenci&eacute; de mani&egrave;re abusive apr&egrave;s avoir remis en cause la l&eacute;galit&eacute; du protocole utilis&eacute;.</p>
            <h2>Une r&eacute;cup&eacute;ration des messages Messenger supprim&eacute;s</h2>
            <p>C&rsquo;est le site Bloomberg qui rapporte cette histoire qui met encore une fois le groupe de Mark Zuckerberg dans l&rsquo;embarras. Brennan Lawson, alors charg&eacute; de filtrer les contenus sur&nbsp;<a href="https://www.01net.com/tag/facebook/">Facebook</a>, aurait pris connaissance de cette proc&eacute;dure de r&eacute;cup&eacute;ration des donn&eacute;es lors d&rsquo;une r&eacute;union qui aurait eu lieu fin 2018. Il aurait imm&eacute;diatement &eacute;mis des doutes sur la l&eacute;galit&eacute; de cette pratique.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>Dans sa plainte, Lawson d&eacute;clare que certains membres de l&rsquo;&eacute;quipe pouvaient&nbsp;<em>&laquo;&nbsp;contourner les protocoles de confidentialit&eacute; normaux de Facebook&nbsp;&raquo;</em>&nbsp;en r&eacute;cup&eacute;rant les donn&eacute;es de l&rsquo;application Messenger que les utilisateurs avaient choisi de supprimer. Si ces affirmations sont av&eacute;r&eacute;es, elles violeraient les r&egrave;gles de confidentialit&eacute; num&eacute;riques de l&rsquo;Union europ&eacute;enne et de la&nbsp;<em>Federal Trade Commission</em>&nbsp;qui exige que les utilisateurs soient inform&eacute;s pr&eacute;cis&eacute;ment de la politique de conservation des donn&eacute;es.</p>
            <p>Toujours selon l&rsquo;ex-employ&eacute;, Facebook utilisait ce protocole pour r&eacute;pondre aux questions des forces de l&rsquo;ordre am&eacute;ricaines afin de connaitre le contenu des conversations de personnes suspectes. Une pratique qui, pour Lawson, visait surtout &agrave;&nbsp;<em>&laquo;&nbsp;garder Facebook dans les bonnes gr&acirc;ces du gouvernement&nbsp;&raquo;.</em></p>
            <h2>3 millions de dollars de dommages et int&eacute;r&ecirc;ts</h2>
            <p>Apr&egrave;s cette r&eacute;union fin 2018, l&rsquo;ex-employ&eacute; n&rsquo;a pas &eacute;t&eacute; remerci&eacute; imm&eacute;diatement par Facebook. En effet, il a &eacute;t&eacute; licenci&eacute; en juillet 2019, officiellement pour utilisation abusive d&rsquo;un outil administratif interne. Une accusation que Brennan Lawson r&eacute;fute et qui pour lui n&rsquo;est qu&rsquo;un pr&eacute;texte et un acte de repr&eacute;sailles suite &agrave; ses plaintes sur l&rsquo;utilisation d&rsquo;un tel protocole par Facebook. Il r&eacute;clame 3 millions de dommages et int&eacute;r&ecirc;ts &agrave; son ex-employeur. Facebook n&rsquo;a pour l&rsquo;instant pas comment&eacute; cette affaire.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>Cette affaire vient s&rsquo;ajouter &agrave;&nbsp;<a href="https://www.01net.com/actualites/facebook-et-les-fuites-de-donnees-personnelles-une-longue-serie-de-fiascos-2040922.html">une longue s&eacute;rie de fuites de donn&eacute;es personnelles par Facebook</a>&nbsp;ces quatre derni&egrave;res ann&eacute;es. La plus retentissante &eacute;tant sans doute celle du&nbsp;<a href="https://www.01net.com/actualites/comment-cambridge-analytica-a-manipule-les-utilisateurs-de-facebook-1439178.html">scandale Cambridge Analytica qui a d&eacute;but&eacute; en mars 2018</a>. Une soci&eacute;t&eacute; avait r&eacute;ussi &agrave; &laquo;&nbsp;aspirer&nbsp;&raquo;&nbsp;les donn&eacute;es de 87 millions d&rsquo;utilisateurs afin de cr&eacute;er leurs profils psychologiques pour faciliter la victoire de Donald Trump aux &eacute;lections pr&eacute;sidentielles.</p>
            <p>Malgr&eacute; ses efforts pour permettre de&nbsp;<a href="https://www.01net.com/astuces/comment-gerer-vos-donnees-collectees-par-facebook-sur-d-autres-sites-web-1849115.html">contr&ocirc;ler l&rsquo;utilisation de vos donn&eacute;es r&eacute;colt&eacute;es en dehors de Facebook</a>, le r&eacute;seau social d&eacute;tient toujours un v&eacute;ritable tr&eacute;sor de donn&eacute;es personnelles sur les utilisateurs de sa plateforme.</p>
            </div>',
            "articleSumary" => "Facebook a eu accès à vos données supprimées, selon cet ancien employé",
            "date" => ""
        ],
        [
            "title" => "La boîte noire est désormais obligatoire dans les voitures.",
            "image" => "https://www.01net.com/app/uploads/2022/06/S8-boite-noire-dans-nos-voitures-ni-grand-progres-ni-inconvenient-majeur-195926.jpg",
            "articleContent" => '<div class="post-excerpt">
            <p>&Agrave; partir du 6 juillet 2022, les v&eacute;hicules neufs vendus en Europe devront &ecirc;tre &eacute;quip&eacute;s d&rsquo;une bo&icirc;te noire, &agrave; l&rsquo;image de celle qui &eacute;quipe d&eacute;j&agrave; les avions. Mais comment fonctionne-t-elle et quel est son but&nbsp;?</p>
            </div>
            <div class="od-wrapper od-background">&nbsp;</div>
            <div class="entry-content prose dark:prose-invert lg:prose-lg max-w-none mt-5">
            <p class="p1">Depuis le 6 juillet, les v&eacute;hicules neufs vendus en Europe devront int&eacute;grer de nouveaux &eacute;quipements de s&eacute;curit&eacute; s&rsquo;ils souhaitent &ecirc;tre homologu&eacute;s. Aide au freinage d&rsquo;urgence, r&eacute;gulateur de vitesse intelligent ou encore assistance au maintien dans la voie font partie du cahier des charges &agrave; respecter. Mais dans la liste des nouveaux &eacute;quipements obligatoires, il en est un qui pose bien plus de questions&nbsp;:&nbsp;<strong>la bo&icirc;te noire</strong>. En effet, les v&eacute;hicules neufs vendus &agrave; partir d&rsquo;aujourd&rsquo;hui devront embarquer un bo&icirc;tier qui sera en mesure d&rsquo;enregistrer diverses donn&eacute;es en cas d&rsquo;accident. Exactement comme les bo&icirc;tes noires des avions.</p>
            <p class="p1">Si l&rsquo;utilit&eacute; du bo&icirc;tier pour comprendre les causes d&rsquo;un accident para&icirc;t &eacute;vidente, il n&rsquo;en demeure pas moins que son int&eacute;gration obligatoire pose des questions. Quelles donn&eacute;es cette bo&icirc;te noire sera-t-elle capable de r&eacute;colter&nbsp;? Comment fonctionne-t-elle&nbsp;? Et, surtout, qui aura acc&egrave;s aux donn&eacute;es apr&egrave;s l&rsquo;accident&nbsp;? On fait le point.</p>
            <p class="p1"><img class="aligncenter size-full wp-image-818919 cursor-pointer" style="display: block; margin-left: auto; margin-right: auto;" src="https://www.01net.com/app/uploads/2015/08/voiture-vitesse-1256.jpg" sizes="(max-width: 1256px) 100vw, 1256px" srcset="https://www.01net.com/app/uploads/2015/08/voiture-vitesse-1256.jpg 1256w, https://www.01net.com/app/uploads/2015/08/voiture-vitesse-1256-300x169.jpg 300w, https://www.01net.com/app/uploads/2015/08/voiture-vitesse-1256-1024x577.jpg 1024w, https://www.01net.com/app/uploads/2015/08/voiture-vitesse-1256-768x433.jpg 768w" alt="" width="1000" height="564" loading="lazy" data-index="0"></p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <h2 class="p1"><strong>Quels v&eacute;hicules embarqueront cette bo&icirc;te noire&nbsp;?</strong></h2>
            <p class="p1">La bo&icirc;te noire sera indispensable &agrave; l&rsquo;homologation d&rsquo;une voiture en Europe. Autrement dit, presque tous les v&eacute;hicules neufs vendus &agrave; partir du 6 juillet pourraient en &ecirc;tre &eacute;quip&eacute;s. Pourquoi cette nuance&nbsp;? Tout simplement parce que la proc&eacute;dure de mise en place se fait en deux temps. Il y a, d&rsquo;une part, l&rsquo;homologation du v&eacute;hicule, puis son immatriculation. Autrement dit, un mod&egrave;le sorti tr&egrave;s r&eacute;cemment, disons l&rsquo;<a href="https://www.01net.com/actualites/audi-q4-sportback-e-tron-on-a-teste-la-moins-chere-des-audi-electriques.html">Audi Q4 e-tron Sportback</a>&nbsp;que nous avons test&eacute; il y a peu, n&rsquo;en sera pas obligatoirement &eacute;quip&eacute;e. Mais toute autre voiture qui serait propos&eacute;e &agrave; l&rsquo;homologation &agrave; partir du 6 juillet, ne pourra pas y &eacute;chapper. Une&nbsp;<a href="https://www.01net.com/actualites/mg4-450-km-dautonomie-et-prix-canon-cette-voiture-electrique-a-tout-pour-faire-un-carton.html">MG4</a>&nbsp;ou une&nbsp;<a href="https://www.01net.com/actualites/hyundai-devoile-le-design-de-la-ioniq-6-sa-berline-electrique-futuriste.html">Hyundai Ioniq 6,</a>&nbsp;par exemple, qui vient d&rsquo;&ecirc;tre annonc&eacute;e, mais qui n&rsquo;a pas encore &eacute;t&eacute; homologu&eacute;e, devra passer par la case bo&icirc;te noire. Enfin, &agrave; partir du 6 juillet 2024, l&rsquo;obligation d&rsquo;int&eacute;grer une bo&icirc;te noire s&rsquo;&eacute;tendra &agrave; tous les v&eacute;hicules neufs, sans exception.</p>
            <p class="p1"><img class="aligncenter size-full wp-image-1091939 cursor-pointer" style="display: block; margin-left: auto; margin-right: auto;" src="https://www.01net.com/app/uploads/2022/06/bmw-3er-2019.jpg" sizes="(max-width: 1920px) 100vw, 1920px" srcset="https://www.01net.com/app/uploads/2022/06/bmw-3er-2019.jpg 1920w, https://www.01net.com/app/uploads/2022/06/bmw-3er-2019-300x169.jpg 300w, https://www.01net.com/app/uploads/2022/06/bmw-3er-2019-1024x576.jpg 1024w, https://www.01net.com/app/uploads/2022/06/bmw-3er-2019-768x432.jpg 768w, https://www.01net.com/app/uploads/2022/06/bmw-3er-2019-1536x864.jpg 1536w, https://www.01net.com/app/uploads/2022/06/bmw-3er-2019-50x28.jpg 50w" alt="" width="1000" height="563" loading="lazy" data-index="1"></p>
            <p class="p1">Cela ne concerne donc pas les v&eacute;hicules d&eacute;j&agrave; en circulation.&nbsp;<strong>Il n&rsquo;est pas n&eacute;cessaire de contacter votre garagiste pour installer le dispositif</strong>. En revanche, si vous achetez une voiture dans les jours ou les mois qui suivent, gardez en t&ecirc;te qu&rsquo;elle en sera peut-&ecirc;tre &eacute;quip&eacute;e. Enfin,&nbsp;<strong>les bo&icirc;tes noires ne seront pas non plus install&eacute;es sur des voitures d&rsquo;occasion</strong>, peu importe la date de leur vente.</p>
            <h2 class="p1"><strong>Comment fonctionne la bo&icirc;te noire automobile&nbsp;?</strong></h2>
            <p class="p1">La bo&icirc;te noire est consid&eacute;r&eacute;e comme un &laquo;&nbsp;dispositif de s&eacute;curit&eacute; automatis&eacute;&nbsp;&raquo;. Autrement dit, elle ne sera en mesure d&rsquo;enregistrer que les donn&eacute;es pour lesquelles elle a &eacute;t&eacute; programm&eacute;e. Selon le R&egrave;glement (UE) 2019/2144 du Parlement Europ&eacute;en,&nbsp;<strong>la bo&icirc;te noire est en mesure d&rsquo;enregistrer les donn&eacute;es pendant les 30 secondes qui pr&eacute;c&egrave;dent l&rsquo;accident et au cours des 10 secondes qui suivent l&rsquo;impact</strong>. Le dispositif n&rsquo;est pas autoris&eacute; &agrave; fonctionner en dehors de ces phases pr&eacute;cises.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <h2 class="p1"><strong>Quelles sont les donn&eacute;es analys&eacute;es par la bo&icirc;te noire des voitures&nbsp;?</strong></h2>
            <p class="p1">La bo&icirc;te noire aura acc&egrave;s aux organes dits sensibles de la voiture (freinage, direction, acc&eacute;l&eacute;rateur, clignotants, etc.). En cons&eacute;quence, elle sera en mesure d&rsquo;enregistrer les donn&eacute;es suivantes&nbsp;:</p>
            <ul>
            <li class="p1">La vitesse</li>
            <li class="p1">Les phases d&rsquo;acc&eacute;l&eacute;ration ou de freinage</li>
            <li class="p1">L&rsquo;activation ou non du clignotant</li>
            <li class="p1">Le port de la ceinture</li>
            <li class="p1">La force de collision</li>
            <li class="p1">Le r&eacute;gime moteur</li>
            <li class="p1">L&rsquo;inclinaison de la voiture</li>
            </ul>
            <p class="p1">En revanche, &agrave; l&rsquo;inverse des bo&icirc;tes noires dans les avions, celle des voitures n&rsquo;est pas capable de capter de l&rsquo;audio, ou plus pr&eacute;cis&eacute;ment les sons dans l&rsquo;habitacle.<img class="aligncenter size-full wp-image-1091936 cursor-pointer" style="display: block; margin-left: auto; margin-right: auto;" src="https://www.01net.com/app/uploads/2022/06/le-geste-qu-il-faut-faire-systematiquement-des-que-l-on-s-assoit-pour-memoire-en-2016-20-des-personnes-tuees-sur-la-route-ne-portaient-pas-la-ceinture-dr-1590163754.jpg" sizes="(max-width: 1181px) 100vw, 1181px" srcset="https://www.01net.com/app/uploads/2022/06/le-geste-qu-il-faut-faire-systematiquement-des-que-l-on-s-assoit-pour-memoire-en-2016-20-des-personnes-tuees-sur-la-route-ne-portaient-pas-la-ceinture-dr-1590163754.jpg 1181w, https://www.01net.com/app/uploads/2022/06/le-geste-qu-il-faut-faire-systematiquement-des-que-l-on-s-assoit-pour-memoire-en-2016-20-des-personnes-tuees-sur-la-route-ne-portaient-pas-la-ceinture-dr-1590163754-300x200.jpg 300w, https://www.01net.com/app/uploads/2022/06/le-geste-qu-il-faut-faire-systematiquement-des-que-l-on-s-assoit-pour-memoire-en-2016-20-des-personnes-tuees-sur-la-route-ne-portaient-pas-la-ceinture-dr-1590163754-1024x682.jpg 1024w, https://www.01net.com/app/uploads/2022/06/le-geste-qu-il-faut-faire-systematiquement-des-que-l-on-s-assoit-pour-memoire-en-2016-20-des-personnes-tuees-sur-la-route-ne-portaient-pas-la-ceinture-dr-1590163754-768x512.jpg 768w, https://www.01net.com/app/uploads/2022/06/le-geste-qu-il-faut-faire-systematiquement-des-que-l-on-s-assoit-pour-memoire-en-2016-20-des-personnes-tuees-sur-la-route-ne-portaient-pas-la-ceinture-dr-1590163754-50x33.jpg 50w, https://www.01net.com/app/uploads/2022/06/le-geste-qu-il-faut-faire-systematiquement-des-que-l-on-s-assoit-pour-memoire-en-2016-20-des-personnes-tuees-sur-la-route-ne-portaient-pas-la-ceinture-dr-1590163754-336x224.jpg 336w" alt="" width="1000" height="666" loading="lazy" data-index="2"></p>
            <h2 class="p1"><strong>Qui aura acc&egrave;s aux donn&eacute;es&nbsp;?</strong></h2>
            <p class="p1">C&rsquo;est &eacute;videmment la question la plus &eacute;pineuse de cette nouvelle mesure. Le site du gouvernement,&nbsp;<a href="https://www.service-public.fr/particuliers/actualites/A15659#:~:text=La%20bo%C3%AEte%20noire%20%C3%A9quipant%20les,accident."><span class="s1">service-public.fr</span></a>, explique que&nbsp;<strong><em>&laquo;&nbsp;seuls les enqu&ecirc;teurs, les autorit&eacute;s judiciaires ou les instituts de recherche devraient avoir acc&egrave;s aux donn&eacute;es de la bo&icirc;te noire&nbsp;&raquo;</em></strong>.<br>Autrement dit, ces donn&eacute;es ne seraient accessibles que sur requ&ecirc;te judiciaire pour d&eacute;terminer, par exemple, les circonstances d&rsquo;un accident grave. Quant aux instituts de recherche, ils pourraient avoir acc&egrave;s &agrave; ces donn&eacute;es &laquo;&nbsp;anonymis&eacute;es&nbsp;&raquo; afin d&rsquo;&eacute;tudier les facteurs d&rsquo;accidents &agrave; plus grande &eacute;chelle.</p>
            <p class="p1"><img class="aligncenter size-full wp-image-1091935 cursor-pointer" style="display: block; margin-left: auto; margin-right: auto;" src="https://www.01net.com/app/uploads/2022/06/B9730792424Z.1_20220503151905_000GS3KDTSM1.1-0.jpg" sizes="(max-width: 1350px) 100vw, 1350px" srcset="https://www.01net.com/app/uploads/2022/06/B9730792424Z.1_20220503151905_000GS3KDTSM1.1-0.jpg 1350w, https://www.01net.com/app/uploads/2022/06/B9730792424Z.1_20220503151905_000GS3KDTSM1.1-0-300x169.jpg 300w, https://www.01net.com/app/uploads/2022/06/B9730792424Z.1_20220503151905_000GS3KDTSM1.1-0-1024x576.jpg 1024w, https://www.01net.com/app/uploads/2022/06/B9730792424Z.1_20220503151905_000GS3KDTSM1.1-0-768x432.jpg 768w, https://www.01net.com/app/uploads/2022/06/B9730792424Z.1_20220503151905_000GS3KDTSM1.1-0-50x28.jpg 50w" alt="" width="1000" height="563" loading="lazy" data-index="3"></p>
            <p class="p1">Et&nbsp;<strong>du c&ocirc;t&eacute; des assureurs&nbsp;? Ils n&rsquo;auront pas acc&egrave;s &agrave; ces donn&eacute;es et ne pourront pas les utiliser</strong>.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p class="p1">N&eacute;anmoins, cela n&rsquo;emp&ecirc;che pas certaines voix de s&rsquo;&eacute;lever contre les nouveaux risques induits par les bo&icirc;tes noires. Ainsi, Pierre Chasseray, d&eacute;l&eacute;gu&eacute; g&eacute;n&eacute;ral de l&rsquo;<em>Association 40 millions d&rsquo;automobilistes</em>&nbsp;explique &agrave; nos confr&egrave;res du&nbsp;<em>Dauphin&eacute;</em>&nbsp;:</p>
            <blockquote>
            <p class="p1">&laquo;&nbsp;<em>En dissimulant un enregistreur de donn&eacute;es dans les voitures, on esp&egrave;re dissuader les mauvais comportements et ainsi limiter les accidents. Mais il ne faut pas prendre les automobilistes pour des imb&eacute;ciles&nbsp;: ils sont parfaitement conscients que tel qu&rsquo;il est con&ccedil;u, ce genre de dispositif ne peut avoir aucun impact sur les infractions et les comportements r&eacute;ellement accidentog&egrave;nes que sont par exemple le refus de priorit&eacute;&nbsp;(16&nbsp;% des accidents mortels), l&rsquo;usage du t&eacute;l&eacute;phone au volant&nbsp;(environ 10&nbsp;%), la somnolence et la perte d&rsquo;attention&nbsp;(10 &agrave; 15&nbsp;%).<br>De plus, les donn&eacute;es enregistr&eacute;es ne sont conserv&eacute;es et &eacute;ventuellement analys&eacute;es qu&rsquo;en cas de choc, 30 secondes avant et 30 secondes apr&egrave;s l&rsquo;&eacute;v&eacute;nement. L&rsquo;outil ne peut donc en aucun cas pr&eacute;venir ou emp&ecirc;cher l&rsquo;accident</em>&nbsp;&raquo;.</p>
            </blockquote>
            <h2 class="p1"><strong>Est-ce le premier dispositif de &laquo;&nbsp;surveillance&nbsp;&raquo; install&eacute; sur les voitures de particuliers&nbsp;?</strong></h2>
            <p class="p1">Contrairement &agrave; ce que l&rsquo;on pourrait penser, il ne s&rsquo;agit pas d&rsquo;une premi&egrave;re sur le territoire europ&eacute;en. Depuis 2020, un autre dispositif, moins connu, mais au potentiel moins pol&eacute;mique, &eacute;quipe les voitures neuves. Il s&rsquo;agit de l&rsquo;OBFCM (<em>Onboard fuel consumption monitoring</em>). Il sert &agrave; mesurer la consommation r&eacute;elle des voitures et de la comparer avec les chiffres annonc&eacute;s lors de leur homologation. Objectif&nbsp;? &Eacute;viter le type de pratiques qui ont abouti au&nbsp;<em>Dieselgate</em>&nbsp;et garantir plus de transparence pour les propri&eacute;taires de voitures.</p>
            <p class="p1"><img class="aligncenter size-full wp-image-1091937 cursor-pointer" style="display: block; margin-left: auto; margin-right: auto;" src="https://www.01net.com/app/uploads/2022/06/S1-boite-noire-ni-grand-progres-ni-inconvenient-majeur-713483.jpg" sizes="(max-width: 705px) 100vw, 705px" srcset="https://www.01net.com/app/uploads/2022/06/S1-boite-noire-ni-grand-progres-ni-inconvenient-majeur-713483.jpg 705w, https://www.01net.com/app/uploads/2022/06/S1-boite-noire-ni-grand-progres-ni-inconvenient-majeur-713483-300x200.jpg 300w, https://www.01net.com/app/uploads/2022/06/S1-boite-noire-ni-grand-progres-ni-inconvenient-majeur-713483-50x33.jpg 50w, https://www.01net.com/app/uploads/2022/06/S1-boite-noire-ni-grand-progres-ni-inconvenient-majeur-713483-336x224.jpg 336w" alt="" width="1000" height="667" loading="lazy" data-index="4"></p>
            <p class="p1">Bien qu&rsquo;il ne s&rsquo;agisse pas d&rsquo;un exemple europ&eacute;en, il est possible de regarder de l&rsquo;autre c&ocirc;t&eacute; de l&rsquo;Atlantique. Aux &Eacute;tats-Unis, les bo&icirc;tes noires &eacute;quipent les v&eacute;hicules depuis 2012.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p class="p1">Enfin, que dire de l&rsquo;<a href="https://www.01net.com/actualites/cette-techno-permet-a-des-vehicules-de-communiquer-entre-eux-pour-sauver-des-vies-1532459.html">e-call</a>&nbsp;introduit en 2018 et qui &eacute;quipe toutes les autos depuis cette ann&eacute;e-l&agrave;&nbsp;? Ce dispositif relie entre elles toutes les voitures connect&eacute;es au r&eacute;seau, gr&acirc;ce &agrave; leur GPS. Son objectif&nbsp;: pr&eacute;venir les secours au plus vite en cas d&rsquo;accident.</p>
            <h2 class="p1"><strong>La bo&icirc;te noire pourra-t-elle &ecirc;tre pirat&eacute;e&nbsp;?</strong></h2>
            <p class="p1">C&rsquo;est l&rsquo;autre question sensible de ce dossier. Dans la mesure o&ugrave; la bo&icirc;te noire n&rsquo;est rien d&rsquo;autre qu&rsquo;un dispositif &eacute;lectronique reli&eacute; &agrave; la voiture, le risque de piratage ne peut pas &ecirc;tre compl&egrave;tement exclu.</p>
            <h2 class="p1"><strong>La bo&icirc;te noire va-t-elle faire augmenter le prix des voitures&nbsp;?</strong></h2>
            <p class="p1">L&rsquo;ajout d&rsquo;un &eacute;quipement suppl&eacute;mentaire dans un v&eacute;hicule implique n&eacute;cessairement un surco&ucirc;t. L&rsquo;<em>Association 40 millions d&rsquo;automobilistes</em>&nbsp;estime qu&rsquo;il pourrait &ecirc;tre de 100 ou 150 euros, mais dans un contexte de hausse g&eacute;n&eacute;ralis&eacute;e du prix des voitures et de leurs &eacute;quipements, cette hausse de tarif, aussi anodine qu&rsquo;elle puisse para&icirc;tre, ne peut &ecirc;tre n&eacute;glig&eacute;e. &Agrave; moins que l&rsquo;utilisateur puisse y trouver son compte autrement&hellip; sur une baisse potentielle de sa prime d&rsquo;assurance.<br>La F&eacute;d&eacute;ration fran&ccedil;aise de l&rsquo;Assurance a d&eacute;j&agrave; annonc&eacute; qu&rsquo;elle ne prendrait pas en compte le dispositif dans l&rsquo;&eacute;laboration de ses tarifs. Mais dans la pratique, l&rsquo;exemple am&eacute;ricain tend &agrave; prouver l&rsquo;inverse puisque le tarif moyen de la prime y a baiss&eacute; depuis l&rsquo;introduction des bo&icirc;tes noires.</p>
            </div>',
            "articleSumary" => "La boîte noire est désormais obligatoire dans les voitures : qu’enregistrera-t-elle vraiment et qui aura accès à ses données ?",
            "date" => ""
        ],
        [
            "title" => "L’ère de la communication quantique",
            "image" => "https://www.01net.com/app/uploads/2022/07/MEA2-Quatum-communications-c-Mit-Tech-Review.jpg",
            "articleContent" => '<div class="post-excerpt">
            <p><span style="font-size: 14pt;"><strong>Non seulement les chercheurs allemands ont maintenu une intrication quantique &agrave; 33 km de distance, mais en plus, ils ont utilis&eacute; une longueur d&rsquo;onde proche de celle actuellement utilis&eacute;e dans la fibre optique classique. Prouvant que les r&eacute;seaux actuels pourrait &ecirc;tre utilis&eacute;s pour les futures communications quantiques. Ce qui nous rapproche un peu plus d&rsquo;un internet quantique et de la garantie de l&rsquo;inviolabilit&eacute; des &eacute;changes d&rsquo;informations.</strong></span></p>
            </div>
            <div class="entry-content prose dark:prose-invert lg:prose-lg max-w-none mt-5">
            <p>Pour nous rapprocher de l&rsquo;&egrave;re des communications quantiques, il faut sans &eacute;loigner sans cesse les atomes intriqu&eacute;s. C&rsquo;est un &eacute;loignement record que des chercheurs allemands viennent de r&eacute;aliser en maintenant l&rsquo;intrication quantique entre deux atomes distants de 33 km. Ces scientifiques des universit&eacute;s de Ludwig-Maximilians (M&uuml;nich) et de la Sarre ont li&eacute; l&rsquo;&eacute;tat de deux atomes de rubidium en utilisant le principe de l&rsquo;intrication quantique, un &eacute;tat dans lequel deux particules voient leur nature &ecirc;tre calqu&eacute;e l&rsquo;une sur l&rsquo;autre. Dans cet &eacute;tat, les deux particules sont indiscernables et toute action sur l&rsquo;une engendre un changement de nature de l&rsquo;autre&hellip; m&ecirc;me &agrave; des kilom&egrave;tres de distance.</p>
            <p>Du point de vue pratique, les chercheurs ont intriqu&eacute; deux atomes de rubidium maintenus dans leurs &laquo;&nbsp;pi&egrave;ges&nbsp;optiques&nbsp;&raquo;. Ces deux atomes &eacute;taient initialement reli&eacute;s par une fibre optique et physiquement plac&eacute;s &agrave; 700 m de distance l&rsquo;un de l&rsquo;autre dans deux b&acirc;timents de l&rsquo;universit&eacute; munichoise. Une fois cet &eacute;tat obtenu, la longueur de la fibre a &eacute;t&eacute; port&eacute;e &agrave; 33 km et l&rsquo;intrication maintenue.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p><img class="alignnone size-full wp-image-1093830 cursor-pointer" style="display: block; margin-left: auto; margin-right: auto;" src="https://www.01net.com/app/uploads/2022/07/41586_2022_4764_Fig1_HTML.webp" sizes="(max-width: 1920px) 100vw, 1920px" srcset="https://www.01net.com/app/uploads/2022/07/41586_2022_4764_Fig1_HTML.webp 1920w, https://www.01net.com/app/uploads/2022/07/41586_2022_4764_Fig1_HTML-300x90.webp 300w, https://www.01net.com/app/uploads/2022/07/41586_2022_4764_Fig1_HTML-1024x309.webp 1024w, https://www.01net.com/app/uploads/2022/07/41586_2022_4764_Fig1_HTML-768x232.webp 768w, https://www.01net.com/app/uploads/2022/07/41586_2022_4764_Fig1_HTML-1536x463.webp 1536w, https://www.01net.com/app/uploads/2022/07/41586_2022_4764_Fig1_HTML-50x15.webp 50w" alt="Le syst&egrave;me optique reliant les deux atomes intriqu&eacute;s. " width="1111" height="335" loading="lazy" data-index="0"></p>
            <p>&nbsp;</p>
            <p>Pour v&eacute;rifier et comparer leur &eacute;tat, les deux atomes ont &eacute;t&eacute; excit&eacute;s par un laser, une proc&eacute;dure qui entra&icirc;ne l&rsquo;&eacute;mission de photons. L&rsquo;int&eacute;r&ecirc;t de la man&oelig;uvre ? Les photons ainsi cr&eacute;&eacute;s sont, eux aussi, intriqu&eacute;s avec l&rsquo;atome d&rsquo;origine. Au milieu du chemin, un r&eacute;cepteur v&eacute;rifie l&rsquo;&eacute;tat des deux photons pour v&eacute;rifier qu&rsquo;ils soient de m&ecirc;me nature.</p>
            <p>L&rsquo;int&eacute;r&ecirc;t de la manipulation est &agrave; chercher dans l&rsquo;une des promesses de la communication quantique&nbsp;:&nbsp;<a href="https://www.01net.com/actualites/cette-societe-pretend-pouvoir-bientot-casser-le-chiffrement-au-coeur-de-la-securite-d-internet-et-des-banques-2033819.html">sa s&eacute;curit&eacute;</a>. Dans les communications actuelles, si un individu pourvu de capacit&eacute;s de d&eacute;chiffrement intercepte vos communications, il peut les lire/&eacute;couter sans &ecirc;tre d&eacute;tect&eacute;. Or, d&egrave;s qu&rsquo;un signal quantique est observ&eacute;, son &eacute;tat change automatiquement et on peut ainsi savoir qu&rsquo;il a &eacute;t&eacute; intercept&eacute;. Plus on arrive &agrave; &eacute;loigner des particules quantiques intriqu&eacute;es, plus on s&rsquo;approche d&rsquo;un monde avec des canaux de communication inviolables. Et extr&ecirc;mement rapide puisque l&rsquo;intrication quantique bouscule les lois physiques de la m&eacute;canique classique &ndash; l&rsquo;intrication quantique est une information qui va plus vite que la vitesse de la lumi&egrave;re.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>Outre la prouesse de maintenir l&rsquo;intrication entre deux particules quantiques &agrave; une si grande distance, l&rsquo;exp&eacute;rience des chercheurs allemands a comme int&eacute;r&ecirc;t de s&rsquo;&ecirc;tre appuy&eacute;e sur de la fibre optique grand public. Alors que leur longueur d&rsquo;onde naturelle est de 780 nm, qui a comme faiblesse de ne porter le signal que sur quelques kilom&egrave;tres, les scientifiques ont r&eacute;ussi &agrave; convertir, de part et d&rsquo;autre, leur longueur d&rsquo;onde &agrave; 1517 nm, soit tr&egrave;s proche de la &laquo;&nbsp;porteuse&nbsp;&raquo; actuelle des r&eacute;seaux photoniques actuels, qui est de 1550 nm. S&rsquo;appuyer sur tout ou partie des infrastructures actuelles sera un &eacute;l&eacute;ment d&eacute;terminant de la vitesse du d&eacute;veloppement des communications quantiques. Cette &eacute;tape est donc tr&egrave;s importante et apportera sans doute avec elle une acc&eacute;l&eacute;ration des exp&eacute;riences sur les r&eacute;seaux classiques occidentaux.</p>
            <p>&nbsp;</p>
            <figure id="attachment_1093831" class="wp-caption alignnone" style="text-align: center;" aria-describedby="caption-attachment-1093831"><img class="size-full wp-image-1093831 cursor-pointer" src="https://www.01net.com/app/uploads/2022/07/theworldsfir.jpg" sizes="(max-width: 800px) 100vw, 800px" srcset="https://www.01net.com/app/uploads/2022/07/theworldsfir.jpg 800w, https://www.01net.com/app/uploads/2022/07/theworldsfir-300x181.jpg 300w, https://www.01net.com/app/uploads/2022/07/theworldsfir-768x463.jpg 768w, https://www.01net.com/app/uploads/2022/07/theworldsfir-50x30.jpg 50w" alt="Le r&eacute;seau de communications quantique des scientifiques et militaires chinois." width="1099" height="662" loading="lazy" data-index="1">
            <figcaption id="caption-attachment-1093831" class="wp-caption-text"><br>Le r&eacute;seau de communications quantique des scientifiques et militaires chinois.</figcaption>
            </figure>
            <p>&nbsp;</p>
            <p>Pourquoi pr&eacute;ciser &laquo; occidentaux &raquo; ? Simplement parce que si la recherche en communication quantique est ouverte dans le monde occidental,&nbsp;<a href="https://phys.org/news/2021-01-world-quantum-network.html">elle est sous contr&ocirc;le militaire en Chine</a>. Un pays qui a d&eacute;j&agrave; con&ccedil;u un r&eacute;seau exp&eacute;rimental de communication quantique m&ecirc;lant signaux satellitaires et pas moins de 4600 km de fibre optique. Un r&eacute;seau dont on conna&icirc;t une partie de la structure, mais dont les usages et le contr&ocirc;le scientifique sont ferm&eacute;s aux civils.</p>
            </div>',
            "articleSumary" => "Des chercheurs allemands nous approchent un peu plus de l’ère de la communication quantique",
            "date" => ""
        ],
        [
            "title" => "Tesla installe du Wi-Fi Starlink sur ses Superchargeurs",
            "image" => "https://www.01net.com/app/uploads/2022/07/vthyjn3379a91-1.jpg",
            "articleContent" => '<div class="post-excerpt">
            <p><span style="font-size: 18pt;"><strong>Tesla entend bien proposer un service de plus sur ses bornes de recharge rapide. Le constructeur californien a d&eacute;but&eacute; le d&eacute;ploiement d&rsquo;antennes Starlink sur les Superchargeurs.</strong></span></p>
            <p>Tesla compte bien s&rsquo;appuyer sur une autre entreprise de son fondateur, Elon Musk, pour &eacute;toffer son offre sur les <a href="https://www.01net.com/actualites/tesla-ouvre-enfin-ses-superchargeurs-aux-vehicules-d-autres-marques-2054210.html">Superchargeurs</a>. Aux &Eacute;tats-Unis, le constructeur automobile et l&rsquo;op&eacute;rateur&nbsp;<a href="https://www.01net.com/actualites/starlink-ces-francais-pour-qui-le-service-dacces-a-internet-delon-musk-a-tout-change.html">Starlink</a>&nbsp;ont commenc&eacute; &agrave; travailler &agrave; l&rsquo;installation d&rsquo;antennes du second sur les Superchargeurs du premier. L&rsquo;objectif annonc&eacute;&nbsp;? Proposer un service suppl&eacute;mentaire sur les stations de charge rapide de la marque, l&agrave; o&ugrave; les temps d&rsquo;attente peuvent &ecirc;tre parfois longs. Le Wi-Fi disponible gratuitement conjugu&eacute; aux nombreuses fonctionnalit&eacute;s de divertissement accessibles via l&rsquo;OS de Tesla (Netflix, Disney+, Spotify, jeux vid&eacute;o, etc.) devrait rendre moins p&eacute;nibles les pauses recharge obligatoires sur les longs trajets.</p>
            </div>
            <div class="entry-content prose dark:prose-invert lg:prose-lg max-w-none mt-5">
            <p class="p1">N&eacute;anmoins, ce volet de connectivit&eacute; des Tesla est une option. Le service est factur&eacute; 9,99 euros par mois. Certes, il est possible de s&rsquo;en passer et d&rsquo;utiliser son smartphone en partage de connexion, mais tous les utilisateurs n&rsquo;y recourent pas n&eacute;cessairement. D&egrave;s lors, l&rsquo;existence d&rsquo;un r&eacute;seau Wi-Fi gratuit pr&egrave;s des Superchargeurs est une offre bienvenue.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <div class="twitter-tweet twitter-tweet-rendered"><iframe id="twitter-widget-0" class="" title="Twitter Tweet" src="https://platform.twitter.com/embed/Tweet.html?creatorScreenName=dimcharitsis&amp;dnt=true&amp;embedId=twitter-widget-0&amp;features=eyJ0ZndfdHdlZXRfZWRpdF9iYWNrZW5kIjp7ImJ1Y2tldCI6Im9mZiIsInZlcnNpb24iOm51bGx9LCJ0ZndfcmVmc3JjX3Nlc3Npb24iOnsiYnVja2V0Ijoib2ZmIiwidmVyc2lvbiI6bnVsbH0sInRmd190d2VldF9yZXN1bHRfbWlncmF0aW9uXzEzOTc5Ijp7ImJ1Y2tldCI6InR3ZWV0X3Jlc3VsdCIsInZlcnNpb24iOm51bGx9LCJ0Zndfc2Vuc2l0aXZlX21lZGlhX2ludGVyc3RpdGlhbF8xMzk2MyI6eyJidWNrZXQiOiJpbnRlcnN0aXRpYWwiLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X2V4cGVyaW1lbnRzX2Nvb2tpZV9leHBpcmF0aW9uIjp7ImJ1Y2tldCI6MTIwOTYwMCwidmVyc2lvbiI6bnVsbH0sInRmd19kdXBsaWNhdGVfc2NyaWJlc190b19zZXR0aW5ncyI6eyJidWNrZXQiOiJvZmYiLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X3VzZXJfZm9sbG93X2ludGVudF8xNDQwNiI6eyJidWNrZXQiOiJmb2xsb3ciLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X3R3ZWV0X2VkaXRfZnJvbnRlbmQiOnsiYnVja2V0Ijoib2ZmIiwidmVyc2lvbiI6bnVsbH19&amp;frame=false&amp;hideCard=false&amp;hideThread=false&amp;id=1448569328060624897&amp;lang=fr&amp;origin=https%3A%2F%2Fwww.01net.com%2Factualites%2Ftesla-installe-du-wi-fi-starlink-sur-ses-superchargeurs.html&amp;sessionId=4c0697dbd7c751e00931e8dea07cdec196882a40&amp;siteScreenName=01net&amp;theme=light&amp;widgetsVersion=3235bd17138fa%3A1657578976990&amp;width=500px" frameborder="0" scrolling="no" allowfullscreen="allowfullscreen" data-tweet-id="1448569328060624897"></iframe></div>
            <p>&nbsp;</p>
            <figure id="attachment_1093791" class="wp-caption aligncenter" style="text-align: center;" aria-describedby="caption-attachment-1093791"><img class="wp-image-1093791 size-full cursor-pointer" style="display: block; margin-left: auto; margin-right: auto;" src="https://www.01net.com/app/uploads/2022/07/tesla-supercharger-stalink-1.jpeg" sizes="(max-width: 1920px) 100vw, 1920px" srcset="https://www.01net.com/app/uploads/2022/07/tesla-supercharger-stalink-1.jpeg 1920w, https://www.01net.com/app/uploads/2022/07/tesla-supercharger-stalink-1-300x135.jpeg 300w, https://www.01net.com/app/uploads/2022/07/tesla-supercharger-stalink-1-1024x461.jpeg 1024w, https://www.01net.com/app/uploads/2022/07/tesla-supercharger-stalink-1-768x346.jpeg 768w, https://www.01net.com/app/uploads/2022/07/tesla-supercharger-stalink-1-1536x691.jpeg 1536w, https://www.01net.com/app/uploads/2022/07/tesla-supercharger-stalink-1-50x23.jpeg 50w" alt="" width="1114" height="501" loading="lazy" data-index="0">
            <figcaption id="caption-attachment-1093791" class="wp-caption-text">Une antenne Starlink dans une station de recharge Tesla aux Etats-Unis &ndash; Reddit</figcaption>
            </figure>
            <p class="p1">En octobre dernier, des terminaux Starlink avaient &eacute;t&eacute; aper&ccedil;us dans quelques stations de recharge de l&rsquo;autre c&ocirc;t&eacute; de l&rsquo;Atlantique. Elon Musk avait alors confirm&eacute; que la strat&eacute;gie de la marque &eacute;tait bien de proposer du Wi-Fi sur ses bornes. Mais depuis cette date, le d&eacute;ploiement semblait avoir &eacute;t&eacute; mis en pause. Jusqu&rsquo;&agrave; la fin de la semaine derni&egrave;re donc, puisqu&rsquo;un utilisateur de Reddit affirme, images &agrave; l&rsquo;appui, que l&rsquo;installation a bien repris.</p>
            <h2 class="p1">Du Wi-Fi sur les Superchargeurs en France&nbsp;?</h2>
            <p class="p1">Si l&rsquo;objectif de Tesla et d&rsquo;Elon Musk para&icirc;t clair, le d&eacute;ploiement semble encore assez al&eacute;atoire. Quant &agrave; savoir si le service sera propos&eacute; en France, c&rsquo;est une certitude dans la mesure o&ugrave; le PDG de Tesla a indiqu&eacute; qu&rsquo;il s&rsquo;agissait d&rsquo;une fonctionnalit&eacute; &eacute;tendue &agrave; ses Superchargeurs. Celle-ci pourrait en outre permettre au constructeur d&rsquo;avoir une plus grande ma&icirc;trise sur la maintenance de ses bornes. Les Superchargeurs n&eacute;cessitent une connexion &agrave; Internet pour fonctionner, ce qui implique que dans la plupart des cas, Tesla a recours &agrave; un op&eacute;rateur concurrent.</p>
            <p class="p1">Par ailleurs, la transformation des Superchargeurs en stations service n&rsquo;a rien d&rsquo;&eacute;tonnant dans la mesure o&ugrave; plusieurs constructeurs automobiles envisagent non seulement de d&eacute;ployer des stations de recharge, mais aussi d&rsquo;en faire des lieux de d&eacute;tente aussi bien que des moyens de g&eacute;n&eacute;rer des revenus suppl&eacute;mentaires. Ainsi, Audi a d&eacute;voil&eacute; son concept de &laquo;&nbsp;<em>Charging Hub</em>&nbsp;&raquo;, une station de recharge haut de gamme dans laquelle les utilisateurs de v&eacute;hicules &eacute;lectriques trouvent &agrave; la fois des bornes pour charger, de quoi se relaxer et se restaurer, mais aussi quelques gadgets de leur marque pr&eacute;f&eacute;r&eacute;e.</p>
            </div>',
            "articleSumary" => "Tesla installe du Wi-Fi Starlink sur ses Superchargeurs",
            "date" => ""
        ],
        [
            "title" => "Uber utilisait un « kill switch »",
            "image" => "https://www.01net.com/app/uploads/2022/07/Uber.jpg",
            "articleContent" => '<div class="post-excerpt">
            <p><span style="font-size: 18pt;"><strong>La firme a eu recours &agrave; ce proc&eacute;d&eacute; d&rsquo;extinction d&rsquo;urgence &agrave; plusieurs reprises en France. Une pratique qui pourrait s&rsquo;apparenter &agrave; de l&rsquo;obstruction &agrave; la justice.</strong></span></p>
            </div>
            <div class="od-wrapper od-background">&nbsp;</div>
            <div class="entry-content prose dark:prose-invert lg:prose-lg max-w-none mt-5">
            <p>Lobbying au plus haut sommet du pouvoir politique fran&ccedil;ais et des institutions europ&eacute;ennes, m&eacute;thodes aux fronti&egrave;res de la l&eacute;galit&eacute;, valorisation de la violence pour servir ses int&eacute;r&ecirc;ts &eacute;conomiques&hellip; Publi&eacute;s depuis hier notamment par&nbsp;<a href="https://www.radiofrance.fr/franceinter/uber-files-revelations-sur-les-methodes-contestables-du-geant-uber-1788855"><em>Radio France</em>&nbsp;</a>et&nbsp;<em>Le Monde</em>, les premiers articles r&eacute;dig&eacute;s gr&acirc;ce aux&nbsp;<em>Uber files</em>&nbsp;montrent &agrave; quel point le g&eacute;ant des VTC a us&eacute; durant des ann&eacute;es de techniques naus&eacute;abondes pour faire avancer la loi &agrave; son avantage et asseoir sa domination dans ce secteur.</p>
            <p>Parmi&nbsp;<a href="https://www.lemonde.fr/uber-files/">tous ces articles passionnants</a>, il y en est un qui nous a particuli&egrave;rement tap&eacute; dans l&rsquo;&oelig;il. Car il montre comment Uber a aussi utilis&eacute; la technologie pour se sortir de situations critiques, notamment plusieurs perquisitions men&eacute;es lors de son si&egrave;ge parisien.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>Un excellent papier de la cellule d&rsquo;investigation de Radio France montre en effet dans le d&eacute;tail comment les dirigeants de la firme ont mis en place un&nbsp;<em>&laquo;&nbsp;kill switch&nbsp;&raquo;</em>&nbsp;(ou &laquo;&nbsp;coupe-circuit&nbsp;&raquo; en bon fran&ccedil;ais), afin d&rsquo;emp&ecirc;cher des yeux indiscrets de mettre la main sur des donn&eacute;es sensibles. Il permettait aux responsables de la firme de rendre inop&eacute;rants les ordinateurs portables en l&rsquo;espace de quelques secondes.</p>
            <p>Radio France raconte par exemple comment, le 16 mars 2015, Uber a fait obstruction &agrave; une arm&eacute;e de 25 policiers de la police judiciaire qui avait d&eacute;barqu&eacute; dans les locaux d&rsquo;Uber France, &agrave; Paris. L&rsquo;entreprise est &agrave; l&rsquo;&eacute;poque la cible d&rsquo;une enqu&ecirc;te du parquet de Paris autour de la l&eacute;galit&eacute; de son service Uber Pop, qui met en relation des clients avec des chauffeurs non professionnels.</p>
            <p>&Agrave; peine les policiers rentr&eacute;s, les ordinateurs du bureau s&rsquo;&eacute;teignent. Les agents les saisissent, mais ils n&rsquo;obtiendront pas grand-chose de leur analyse&nbsp;: ces ordinateurs ont &eacute;t&eacute; d&eacute;sactiv&eacute;s &agrave; distance, apr&egrave;s qu&rsquo;un responsable fran&ccedil;ais d&rsquo;Uber a envoy&eacute; un message en urgence &agrave; sa hi&eacute;rarchie. De &laquo;&nbsp;<em>hauts responsables</em>&nbsp;&raquo; d&rsquo;Uber commenteront ensuite, dans un SMS, vu par les journalistes de Radio France&nbsp;: &laquo;&nbsp;<em>L&rsquo;acc&egrave;s aux outils informatiques a &eacute;t&eacute; coup&eacute; imm&eacute;diatement. La police ne pourra pas r&eacute;cup&eacute;rer grand-chose, voire rien du tout</em>.&nbsp;&raquo;</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <h2><strong>&laquo;&nbsp;Activez le kill switch imm&eacute;diatement&nbsp;&raquo;</strong></h2>
            <p>Uber a eu recours &agrave; cette technique &agrave; plusieurs reprises et ce d&egrave;s 2014, d&rsquo;apr&egrave;s Radio France, alors que la DGCCRF interroge trois employ&eacute;s de la firme &agrave; Lyon.&nbsp;<em>&laquo;&nbsp;Nous avons coup&eacute; leur acc&egrave;s et envoyons un avocat d&egrave;s que possible&nbsp;&raquo;&nbsp;</em>&eacute;crit alors Zac de Kievit, &agrave; l&rsquo;&eacute;poque directeur juridique &laquo;&nbsp;Europe&nbsp;&raquo; d&rsquo;Uber.</p>
            <p>Les documents internes de l&rsquo;entreprise montrent aussi que ce&nbsp;<em>&laquo;&nbsp;kill switch&nbsp;&raquo;</em>&nbsp;&eacute;tait loin d&rsquo;&ecirc;tre r&eacute;serv&eacute; &agrave; la France, puisqu&rsquo;il a &eacute;t&eacute; d&eacute;clench&eacute; dans sept pays, dont l&rsquo;Inde, le Canada, la Belgique&hellip; et aux Pays-Bas. Un pays &laquo;&nbsp;cl&eacute;&nbsp;&raquo; pour Uber, car c&rsquo;est l&agrave;-bas que se trouve son si&egrave;ge international.</p>
            <p>Perquisitionn&eacute; &agrave; plusieurs reprises &ndash; l&agrave; encore &agrave; l&rsquo;occasion d&rsquo;une enqu&ecirc;te autour d&rsquo;Uber Pop &ndash; le si&egrave;ge d&rsquo;Amsterdam a ainsi droit aux messages direct du grand patron, Travis Kalanick&nbsp;<em>himself.&nbsp;</em>Le 2 avril 2015, &agrave; l&rsquo;occasion d&rsquo;une nouvelle descente de police, il envoie &agrave; ses &eacute;quipes un courriel sans &eacute;quivoque&nbsp;:&nbsp;<em>&laquo;&nbsp;Activez le kill switch imm&eacute;diatement&hellip; L&rsquo;acc&egrave;s d&rsquo;Amsterdam doit &ecirc;tre coup&eacute;&nbsp;&raquo;.</em></p>
            <h2><strong>Uber fait son mea culpa</strong></h2>
            <p>Travis Kalanick a quitt&eacute; l&rsquo;entreprise en 2017 et depuis, Uber cherche &agrave; redorer son blason,&nbsp;<a href="https://www.01net.com/actualites/les-cinq-plaies-d-uber-1123211.html">terni par une multitude d&rsquo;affaires</a>&nbsp;bien avant que l&rsquo;on ne d&eacute;couvre ces documents. La firme a notamment tenu &agrave; dire &agrave; Radio France qu&rsquo;elle ne &laquo;&nbsp;<em>disposait</em>&nbsp;plus&nbsp;<em>d&rsquo;un &lsquo;coupe-circuit&rsquo;&nbsp;</em>(Kill switch)<em>&nbsp;con&ccedil;u pour d&eacute;jouer les enqu&ecirc;tes r&eacute;glementaires &agrave; travers le monde, et ce depuis que Dara Khosrowshahi est devenu PDG d&rsquo;Uber en ao&ucirc;t 2017&nbsp;&raquo;.&nbsp;</em>Elle rappelle qu&rsquo;elle continue &agrave; utiliser ces technologies dans certaines situations &ndash; un vol d&rsquo;ordinateur portable, par exemple -, ce qui est logique. Mais, pr&eacute;cise-t-elle, &laquo;&nbsp;<em>il n&rsquo;aurait jamais d&ucirc; &ecirc;tre utilis&eacute; de la mani&egrave;re dont il l&rsquo;a &eacute;t&eacute;.&nbsp;&raquo;</em></p>
            <p>Un&nbsp;<em>mea culpa</em>&nbsp;qui s&rsquo;inscrit dans un cadre bien plus large. Dans un communiqu&eacute;, la firme va jusqu&rsquo;&agrave; dire qu&rsquo;elle ne &laquo;&nbsp;<em>cherche pas d&rsquo;excuses pour des comportements qui ne sont pas conformes &agrave; nos valeurs actuelles en tant qu&rsquo;entreprise. Nous demandons au public de nous juger sur ce que nous avons fait au cours des cinq derni&egrave;res ann&eacute;es et sur ce que nous ferons dans les ann&eacute;es &agrave; venir.&nbsp;&raquo;&nbsp;</em>Dont acte.</p>
            </div>',
            "articleSumary" => "Uber utilisait un « kill switch » pour neutraliser ses ordinateurs à distance en cas de perquisition",
            "date" => ""
        ],
        [
            "title" => "Volkswagen va s’appuyer sur Bosch pour apporter la conduite « sans les mains »",
            "image" => "https://www.01net.com/app/uploads/2019/09/volkswagen-id3-1st-2019-27-1024x592-1.jpg",
            "articleContent" => '<div class="post-excerpt">
            <p><strong><span style="font-size: 18pt;">Bosch et VW vont coop&eacute;rer afin de mettre au point une solution logicielle permettant d&rsquo;acc&eacute;der &agrave; l&rsquo;autonomie de niveau 3 et 4.</span></strong></p>
            </div>
            <div class="od-wrapper od-background">&nbsp;</div>
            <div class="entry-content prose dark:prose-invert lg:prose-lg max-w-none mt-5">
            <p class="p1">Le Bundeskartellamt, le gendarme de la concurrence en Allemagne, a d&eacute;cid&eacute; d&rsquo;autoriser la coop&eacute;ration entre deux figures majeures de l&rsquo;industrie allemande, Bosch et&nbsp;<a href="https://www.01net.com/actualites/volkswagen-s-allie-avec-microsoft-pour-accelerer-sur-la-voiture-autonome-2034401.html">Volkswagen</a>. Les deux marques avaient fait part de leur intention de collaborer dans le d&eacute;veloppement d&rsquo;une solution logicielle permettant d&rsquo;atteindre l&rsquo;autonomie de niveau 3 et 4 en voiture. L&rsquo;autorit&eacute; f&eacute;d&eacute;rale a donc donn&eacute; son feu vert sous certaines conditions&nbsp;: &laquo;&nbsp;<em>la coop&eacute;ration en question est &eacute;tablie pour les seuls fait de recherche et d&eacute;veloppement&nbsp;</em>&raquo;, pr&eacute;cise le communiqu&eacute; du Bundeskartellamt.</p>
            <p class="p1">Par ailleurs, ce n&rsquo;est pas directement Volkswagen, mais sa filiale Cariad qui travaillera avec&nbsp;<a href="https://www.01net.com/actualites/velo-electrique-bosch-lance-son-nouveau-systeme-d-assistance-personnalisable-et-connecte-2047812.html">Bosch</a>. Leur objectif&nbsp;? D&eacute;velopper une solution logicielle capable d&rsquo;une perception vid&eacute;o &agrave; 360&deg; autour de la voiture et d&rsquo;une analyse en temps r&eacute;el. Cette &eacute;tape apparait comme la condition&nbsp;<em>sine qua non</em>&nbsp;pour parvenir aux niveaux d&rsquo;autonomie 3 et 4, c&rsquo;est-&agrave;-dire une conduite sans les mains, dans un environnement limit&eacute; d&rsquo;abord&hellip; et presque dans toutes les circonstances, par la suite. En effet, l&rsquo;autonomie de niveau 3 autorise le conducteur &agrave; se d&eacute;tourner de la route dans certaines conditions, sur des portions d&rsquo;autoroute par exemple. Quant &agrave; l&rsquo;autonomie de niveau 4, il s&rsquo;agit de la derni&egrave;re &eacute;tape avant l&rsquo;autonomie compl&egrave;te et permet m&ecirc;me de faire rouler un v&eacute;hicule sans la pr&eacute;sence d&rsquo;un conducteur.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <h2>Sur les prochaines VW, mais pas seulement</h2>
            <p class="p1">La collaboration entre les deux groupes avait &eacute;t&eacute; annonc&eacute;e une premi&egrave;re fois en d&eacute;but d&rsquo;ann&eacute;e avant que l&rsquo;autorit&eacute; de la concurrence n&rsquo;interroge le bien fond&eacute; de cette alliance de circonstance. &Agrave; l&rsquo;&eacute;poque, l&rsquo;ambition de Volkswagen &eacute;tait de s&rsquo;appuyer sur le savoir-faire de Bosch pour d&eacute;velopper rapidement l&rsquo;autonomie de niveau 3. Le projet pr&eacute;voyait un premier d&eacute;ploiement d&egrave;s 2023, puis un travail sur la dur&eacute;e pour aboutir &agrave; l&rsquo;&eacute;tape suivante. Maintenant que les derniers obstacles sont lev&eacute;s, Volkswagen va pouvoir communiquer sur les premi&egrave;res int&eacute;grations logicielles &agrave; venir. En revanche, si la solution d&eacute;velopp&eacute;e par les deux marques &eacute;quipera d&rsquo;abord les v&eacute;hicules du groupe VW, elles devraient la mettre &agrave; disposition des constructeurs qui souhaiteraient en profiter, moyennant un tarif qui n&rsquo;a pas encore &eacute;t&eacute; fix&eacute;.</p>
            <p class="p1">En d&eacute;finitive, alors que Tesla semblait avoir pris une avance consid&eacute;rable en mati&egrave;re d&rsquo;aides &agrave; la conduite, l&rsquo;Allemagne apparait comme le pays &agrave; la pointe de la recherche sur la voiture autonome. Mercedes est sans doute le constructeur le mieux plac&eacute; dans cette course, mais avec Volkswagen qui acc&eacute;l&egrave;re, il aura fort &agrave; faire.</p>
            </div>',
            "articleSumary" => "Volkswagen va s’appuyer sur Bosch pour apporter la conduite « sans les mains » dans ses voitures",
            "date" => ""
        ],
        [
            "title" => "« batterie de sable »",
            "image" => "https://www.01net.com/app/uploads/2022/07/Batterie-sable-1.jpg",
            "articleContent" => '<div class="post-excerpt">
            <p style="text-align: center;"><strong><span style="font-size: 18pt;">Des ing&eacute;nieurs finlandais ont mis au point une &laquo;&nbsp;batterie&nbsp;&raquo; au sable, capable de conserver l&rsquo;&eacute;nergie renouvelable produite pendant plusieurs mois sous forme de chaleur &agrave; des fins individuelles, collectives ou industrielles.</span></strong></p>
            </div>
            <div class="od-wrapper od-background">&nbsp;</div>
            <div class="entry-content prose dark:prose-invert lg:prose-lg max-w-none mt-5">
            <p>Dans son rapport final&nbsp;<a href="https://www.rte-france.com/analyses-tendances-et-prospectives/bilan-previsionnel-2050-futurs-energetiques">Futurs &eacute;nerg&eacute;tiques 2050</a>, publi&eacute; en f&eacute;vrier dernier, RTE, pour R&eacute;seau de transport d&rsquo;&eacute;lectricit&eacute;, rappelait que la&nbsp;<em>&laquo;&nbsp;variabilit&eacute; de la production</em>&nbsp;(des &eacute;nergies renouvelables, NDLR)&nbsp;<em>doit &ecirc;tre compens&eacute;e par des moyens de flexibilit&eacute;&nbsp;&raquo;</em>, comprendre des solutions pour stocker l&rsquo;&eacute;nergie produite afin de pouvoir en b&eacute;n&eacute;ficier quand le r&eacute;seau en a besoin. Un besoin qui n&rsquo;est pas forc&eacute;ment concomitant &agrave; la production. Le vent souffle quand il le veut et le soleil ne se montre pas toujours quand on le souhaite.</p>
            <h2><strong>L&rsquo;incertitude du renouvelable</strong></h2>
            <p>Pour illustrer cette variabilit&eacute;, il suffit de se tourner vers d&rsquo;autres chiffres fournis par RTE en f&eacute;vrier dernier, toujours. Ainsi, en 2021, les &eacute;nergies renouvelables ont pes&eacute; moins lourd que l&rsquo;ann&eacute;e pr&eacute;c&eacute;dente, malgr&eacute; une augmentation des fermes solaires, notamment. La faute &agrave; des conditions m&eacute;t&eacute;orologiques d&eacute;favorables aussi bien pour l&rsquo;hydraulique que pour l&rsquo;&eacute;olien.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>Que ce soit des r&eacute;servoirs d&rsquo;eau gigantesques, qui servent &agrave; produire de l&rsquo;&eacute;lectricit&eacute; quand le r&eacute;seau est sollicit&eacute; et dont l&rsquo;eau est remont&eacute;e ensuite dans la partie haute &agrave; l&rsquo;aide d&rsquo;&eacute;lectricit&eacute; produite quand les besoins sont moins &eacute;lev&eacute;s ou de batteries plus classiques, l&rsquo;enjeu est de trouver un moyen d&rsquo;utiliser l&rsquo;&eacute;nergie renouvelable de mani&egrave;re optimale et de la stocker avec le moins de d&eacute;perdition possible.</p>
            <h2><strong>Trouver une batterie low tech mais &eacute;conomique</strong></h2>
            <p>Le probl&egrave;me du stockage est qu&rsquo;il faut souvent recourir &agrave; des batteries &laquo;&nbsp;classiques&nbsp;&raquo;, qui contiennent du Lithium, ce qui limite a un co&ucirc;t assez &eacute;lev&eacute;, d&rsquo;autant que ces gigabatteries occupent beaucoup de place.</p>
            <p>N&eacute;anmoins, de jeunes ing&eacute;nieurs finlandais ont peut-&ecirc;tre trouv&eacute; une solution originale, &eacute;cologique et efficace. Leur soci&eacute;t&eacute;&nbsp;<em>Polar Night Energy</em>&nbsp;a d&eacute;velopp&eacute; des &laquo;&nbsp;batteries&nbsp;&raquo; au sable.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>Dans les faits, en fait de batterie, il s&rsquo;agit d&rsquo;un silo, qui ressemble &agrave; un silo &agrave; grains, dans lequel est d&eacute;vers&eacute; du sable de construction, on ne peut plus normal. Ce sable va &ecirc;tre ensuite chauff&eacute; et maintenu &agrave; une temp&eacute;rature entre 300 et 500&deg;C gr&acirc;ce &agrave; un faible courant &eacute;lectrique, produit par des sources renouvelables. Comme le sable accumule et conserve tr&egrave;s bien la chaleur, ces &laquo;&nbsp;conteneurs&nbsp;&raquo; de sable chaud peuvent conserver leur contenu chaud pendant plusieurs mois.</p>
            <p>Quand la production d&rsquo;&eacute;lectricit&eacute; devient plus co&ucirc;teuse &agrave; cause de la demande hivernale, par exemple, l&rsquo;air qui est chauff&eacute; par la &laquo;&nbsp;batterie&nbsp;&raquo; au sable est utilis&eacute; pour chauffer &agrave; son tour l&rsquo;eau du syst&egrave;me thermique des maisons, bureaux et piscines alentours. L&rsquo;&eacute;lectricit&eacute; n&rsquo;est pas stock&eacute;e &agrave; proprement parler, donc, l&rsquo;&eacute;nergie produite et transform&eacute;e l&rsquo;est.</p>
            <p>&nbsp;</p>
            <div class="video-container not-prose"><iframe title="PNE How it Works" src="https://www.youtube.com/embed/LJNlt65un40?feature=oembed" width="500" height="281" frameborder="0" allowfullscreen="allowfullscreen" loading="lazy"></iframe></div>
            <p>&nbsp;</p>
            <h2><strong>Une &eacute;tape de plus, une nouvelle solution</strong></h2>
            <p>Les deux prochaines &eacute;tapes du d&eacute;veloppement de cette technologie&nbsp;<em>low tech</em>&nbsp;seront primordiales. La premi&egrave;re est de savoir si ces &eacute;changeurs de chaleur au sable pourront &ecirc;tre adapt&eacute;s &agrave; des usages plus larges et adopt&eacute;s par des communaut&eacute;s plus grandes. La seconde est de savoir si les deux ing&eacute;nieurs arriveront &agrave; trouver une solution pour am&eacute;liorer la restitution de l&rsquo;&eacute;nergie sous forme d&rsquo;&eacute;lectricit&eacute;. Pour l&rsquo;heure, le rendement est assez faible.</p>
            <div class="od-wrapper od-background">&nbsp;</div>
            <p>N&eacute;anmoins, la chaleur est une forme d&rsquo;&eacute;nergie qui peut avoir de vrais usages dans de nombreux contextes industriels, que ce soit pour la pr&eacute;paration de nourriture, la fabrication de produits pharmaceutiques ou m&ecirc;me la production de textile.</p>
            <p>Ces batteries ne sont &eacute;videmment pas une r&eacute;volution, elles ne r&eacute;soudront pas &agrave; elles seules la question du stockage des &eacute;nergies renouvelables, mais elles apportent leur pierre &agrave; l&rsquo;&eacute;difice, leur petit grain de&hellip; sable.</p>
            </div>',
            "articleSumary" => "Et si cette « batterie de sable » était une nouvelle solution pour lutter contre le réchauffement climatique ?",
            "date" => ""
        ],

    ];

    public function load(ObjectManager $manager): void
    {

        $articleNumber = 1;

        foreach (self::ARTICLES as $articlesDetails) {
                $article = new Articles();
                $article
                ->setTitle($articlesDetails['title'])
                ->setImage($articlesDetails['image'])
                ->setArticleContent($articlesDetails['articleContent'])
                ->setArticleSumary($articlesDetails['articleSumary'])
                ->setDate();
                $manager->persist($article);
                $this->addReference('article_' . $articleNumber, $article);
                $articleNumber++;
        }
        $manager->flush();


        $faker = Factory::create();

        for ($i = 0; $i < 50; $i++) {
            $articles = new Articles();
            $articles->setTitle($faker->text(80));
            $articles->setImage($faker->imageUrl());
            $articles->setArticleContent($faker->paragraph(500));
            $articles->setArticleSumary($faker->text(360));
            $articles->setDate();
            $manager->persist($articles);
        }

        $manager->flush();
    }
}

// @codingStandardsIgnoreEnd
